<?php
/**
 * Template Name: COA Reports Page
 *
 * @package VitalPep_Pro
 */

get_header();
?>

<section class="page-hero">
    <div class="hex-overlay"></div>
    <div class="container">
        <span class="section-label" style="justify-content: center;">Quality Assurance</span>
        <h1 class="page-hero__title">Certificates of Analysis</h1>
        <p class="page-hero__subtitle">Independent third-party lab reports verifying the purity, identity, and sterility of every FlexPen batch produced at our Netherlands facility.</p>
    </div>
</section>

<!-- Explanation -->
<section class="section section--light">
    <div class="container">
        <div style="max-width: 800px; margin: 0 auto 60px; text-align: center;">
            <h2 class="section-title" style="font-size: 1.75rem;">Every Batch. <span>Every Time.</span></h2>
            <p class="section-subtitle" style="margin: 0 auto;">
                Each Certificate of Analysis (COA) is generated by independent, accredited third-party laboratories. Reports include HPLC purity analysis, mass spectrometry confirmation, endotoxin screening, sterility verification, and appearance/pH testing.
            </p>
        </div>

        <!-- Testing Protocol Cards -->
        <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 24px; margin-bottom: 80px;">
            <div class="value-card">
                <div class="value-card__icon">
                    <svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"/></svg>
                </div>
                <h3 class="value-card__title">HPLC Purity Analysis</h3>
                <p class="value-card__text">High-performance liquid chromatography confirms minimum 99%+ purity for every compound across all batch productions.</p>
            </div>
            <div class="value-card">
                <div class="value-card__icon">
                    <svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z"/></svg>
                </div>
                <h3 class="value-card__title">Mass Spectrometry</h3>
                <p class="value-card__text">MS/MS verification confirms molecular identity and weight, ensuring each FlexPen contains the exact specified compound.</p>
            </div>
            <div class="value-card">
                <div class="value-card__icon">
                    <svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"/></svg>
                </div>
                <h3 class="value-card__title">Sterility & Endotoxin</h3>
                <p class="value-card__text">LAL endotoxin testing and sterility assays verify each FlexPen meets pharmaceutical-grade cleanliness standards.</p>
            </div>
        </div>

        <!-- COA List -->
        <div style="margin-bottom: 32px;">
            <span class="section-label">Available Reports</span>
            <h2 class="section-title" style="font-size: 1.5rem;">Recent Batch <span>COA Reports</span></h2>
        </div>

        <div class="coa-grid">
            <?php
            $coa_items = array(
                array( 'name' => 'GHK-Cu FlexPen', 'batch' => 'NL-2026-0342', 'status' => 'Verified' ),
                array( 'name' => 'BPC-157 FlexPen', 'batch' => 'NL-2026-0338', 'status' => 'Verified' ),
                array( 'name' => 'TB-500 FlexPen', 'batch' => 'NL-2026-0335', 'status' => 'Verified' ),
                array( 'name' => 'Semaglutide FlexPen', 'batch' => 'NL-2026-0331', 'status' => 'Verified' ),
                array( 'name' => 'Tirzepatide FlexPen', 'batch' => 'NL-2026-0327', 'status' => 'Verified' ),
                array( 'name' => 'Sermorelin FlexPen', 'batch' => 'NL-2026-0324', 'status' => 'Verified' ),
                array( 'name' => 'Ipamorelin FlexPen', 'batch' => 'NL-2026-0320', 'status' => 'Verified' ),
                array( 'name' => 'Epithalon FlexPen', 'batch' => 'NL-2026-0317', 'status' => 'Verified' ),
                array( 'name' => 'PT-141 FlexPen', 'batch' => 'NL-2026-0312', 'status' => 'Verified' ),
                array( 'name' => 'NAD+ FlexPen', 'batch' => 'NL-2026-0308', 'status' => 'Verified' ),
                array( 'name' => 'Semax FlexPen', 'batch' => 'NL-2026-0305', 'status' => 'Verified' ),
                array( 'name' => 'Selank FlexPen', 'batch' => 'NL-2026-0301', 'status' => 'Verified' ),
            );

            foreach ( $coa_items as $coa ) :
            ?>
            <div class="coa-card">
                <div class="coa-card__icon">
                    <svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
                </div>
                <div>
                    <div class="coa-card__name"><?php echo esc_html( $coa['name'] ); ?></div>
                    <div class="coa-card__batch">Batch: <?php echo esc_html( $coa['batch'] ); ?></div>
                </div>
                <div class="coa-card__status">
                    <svg width="12" height="12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4"/></svg>
                    <?php echo esc_html( $coa['status'] ); ?>
                </div>
            </div>
            <?php endforeach; ?>
        </div>

        <div class="text-center" style="margin-top: 48px;">
            <p style="color: var(--vp-gray-400); font-size: 0.875rem;">
                To request a specific batch COA report not listed above, please <a href="<?php echo esc_url( home_url( '/contact/' ) ); ?>" style="color: var(--vp-accent); text-decoration: underline;">submit an inquiry</a>.
            </p>
        </div>
    </div>
</section>

<?php get_footer(); ?>
